window:
  dimensions:
    columns: 80
    lines: 24
  padding:
    x: 25
    y: 25
scrolling:
  multiplier: 1

font:
  normal:
    family: Fantasque Sans Mono
    style: Regular
  bold:
    family: Fantasque Sans Mono
    style: Bold
  italic:
    family: Fantasque Sans Mono
    style: Italic
  bold_italic:
    family: Fantasque Sans Mono
    style: Bold Italic
  size: 11.0

#background_opacity: 0.85
