#! /bin/sh

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width          0
bspc config window_gap            25
#bspc config top_padding           25
bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       false 
bspc config focus_follows_pointer true

bspc rule -a feh state=floating
bspc rule -a krita state=floating
bspc rule -a blender state=floating
bspc rule -a obs state=floating
bspc rule -a sxiv state=pseudo_tiled
bspc rule -a mpv state=pseudo_tiled

killall -w sxhkd picom &
sleep 0.1
picom &
feh --bg-fill --no-fehbg --randomize ~/Images/Wallpapers
sxhkd
