#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x picom > /dev/null || picom --config /dev/null --backend glx \
	--glx-no-stencil --glx-no-rebind-pixmap --experimental-backends \
	--xrender-sync-fence --use-damage --vsync &
	
bspc monitor ^1 -d 1 2 3 4 5
bspc monitor ^2 -d 6 7 8 9 0

bspc config window_gap            0
bspc config border_width          2
bspc config split_ratio           0.5
bspc config focused_border_color  '#8a93ff'
bspc config active_border_color   '#1d1f21'
bspc config normal_border_color   '#1d1f21'
#bspc config focus_follows_pointer true

bspc rule -r "*"

bspc rule -a Zathura state=tiled
bspc rule -a feh state=pseudo_tiled
bspc rule -a sxiv state=pseudo_tiled
bspc rule -a mpv state=pseudo_tiled

feh --bg-fill --no-fehbg --randomize ~/Images/Wallpapers
