#! /bin/sh

# If these programs are already running, don't run them again.
pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x picom > /dev/null || picom &
	
# Sets every desktop onto monitor one
bspc monitor ^1 -d 1 2 3 4 5 6 7 8 9 0

# For two or more monitors do the following:
# First check monitor names by running:
#    bspc query -M --names
# Then add the following to this file:
#    bspc monitor DVI-I-1 -d 1 2 3 4 5
#    bspc monitor HDMI-0 -d 6 7 8 9 0
# Make sure you use your own monitor names.

# If you want a more portable setup, use monitor numbers:
#    bspc monitor ^1 -d 1 2 3 4 5
#    bspc monitor ^2 -d 6 7 8 9 0
# ^1 is the leftmost monitor. Desktop 1 will always be assigned to it.

# If your monitors are flowing in the wrong direction:
# First check monitor names by running:
#    bspc query -M --names
# Then add the following to this file:
#    xrandr --output DVI-I-1 --left-of HDMI-0
# Make sure you use your own monitor names.

bspc config window_gap            0 
#bspc config gapless_monocle       true

# If you will use a status bar, set this.
#bspc config top_padding           25

bspc config border_width          2
bspc config focused_border_color  "#8a93ff"
bspc config normal_border_color   "#1d1f21"
bspc config split_ratio           0.5
bspc config focus_follows_pointer true

bspc rule -r "*"

bspc rule -a Zathura state=tiled
bspc rule -a feh state=pseudo_tiled
bspc rule -a sxiv state=pseudo_tiled
bspc rule -a mpv state=pseudo_tiled

# Have feh set the wallpaper here.
#feh --bg-fill --no-fehbg --randomize ~/path/to/wallpapers
