#!/bin/sh

# Ctrl-x Ctrl-r to rename the image 
# Ctrl-x Ctrl-c to copy the image (png only)
# Ctrl-x Ctrl-w to set the current image as the wallpaper
# Ctrl-x Ctrl-D to delete the image

while read -r file
do
    case "$1" in
        "C-r")
                name="$(rofi -l 0 -location 7 -xoffset 25 -yoffset -25 -m -1 -dmenu -p "rename $file to: ")" 2> /dev/null
                if ! [ -z "$name" ]; then
                    mv "$file" "$name"
                fi
                ;;
        "C-c")
                xclip -se c -t image/png "$file" ;;
        "C-w")
                feh --bg-fill --no-fehbg "$file" ;;
        "C-D")
                rm "$file" ;;
        *)
                echo "Undefined Key"
                exit 1
                ;;
    esac
done
